name: Test and build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16 ]
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

  build:
    strategy:
      matrix:
        go-version: [ 1.16 ]
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}

    needs: [ test ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Install dependencies
        run: |
          go get -v -t -d ./...

      - name: Run build
        run: mkdir -p ./build && go build -o ./build -v ./...
