name: Release

on:
  create:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          workdir: ./cmd/orchestrator
          args: release --rm-dist --config ../../.github/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          workdir: ./cmd/lukso
          args: release --rm-dist --config ../../.github/.goreleaser-lukso.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Request Multinet Upgrade
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          export GH_TAG=${GITHUB_REF/refs\/tags\//};
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"event_type":"upgrade dev", "client_payload": {"repository": "ORCHESTRATOR", "tag": "'$GH_TAG'"}}' \
          -u "$GITHUB_TOKEN" \
          https://api.github.com/repos/lukso-network/l16-multinet/dispatches

